
// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://gwuexaxuvcmtdcyrjzzz.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Imd3dWV4YXh1dmNtdGRjeXJqenp6Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDYzODk3OTQsImV4cCI6MjA2MTk2NTc5NH0.EkL6ioCjoFDmxadmXg8q1fL-EgO2_OdsILVkEQeis3A";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    autoRefreshToken: true,
    persistSession: true,
    detectSessionInUrl: true,
    flowType: 'pkce' // This is important for OAuth flows
  }
});
