
import { CVScore, CVTip } from "@/lib/types";
import jsPDF from "jspdf";

// Generate a PDF report from the CV analysis
export const generatePdfReport = (score: CVScore, tips: CVTip[], tier: string): void => {
  try {
    // Create a new PDF document
    const doc = new jsPDF();
    const pageWidth = doc.internal.pageSize.getWidth();
    const pageHeight = doc.internal.pageSize.getHeight();
    
    // Add header
    doc.setFillColor(0, 48, 87); // sa-blue in RGB
    doc.rect(0, 0, pageWidth, 30, 'F');
    doc.setTextColor(255, 255, 255);
    doc.setFontSize(22);
    doc.text('ATSBoost CV Report', pageWidth / 2, 20, { align: 'center' });
    
    // Add score section
    doc.setTextColor(0, 48, 87);
    doc.setFontSize(18);
    doc.text(`Overall ATS Score: ${score.overall}`, 20, 50);
    
    // Add score description
    let scoreDescription = '';
    if (score.overall >= 80) {
      scoreDescription = 'Excellent! Your CV is ATS-friendly.';
    } else if (score.overall >= 60) {
      scoreDescription = 'Good start. Follow our tips to improve further.';
    } else {
      scoreDescription = 'Needs improvement. See our recommendations below.';
    }
    
    doc.setFontSize(12);
    doc.text(scoreDescription, 20, 60);
    
    // Add subscores if premium
    if (tier === 'premium' || tier === 'pay-per-use') {
      doc.setFontSize(14);
      doc.text('Detailed Scores:', 20, 80);
      
      doc.setFontSize(12);
      let yPos = 90;
      
      // Display all available scores
      const scoreCategories = [
        { key: 'keywordMatch', label: 'Keywords' },
        { key: 'formatting', label: 'Formatting' },
        { key: 'sectionPresence', label: 'Section Presence' },
        { key: 'readability', label: 'Readability' },
        { key: 'length', label: 'Length' },
        { key: 'bbbeeCompliance', label: 'B-BBEE Compliance' },
        { key: 'contentRelevance', label: 'Content Relevance' }
      ];
      
      scoreCategories.forEach(category => {
        if (score[category.key] !== undefined) {
          doc.text(`${category.label}: ${score[category.key]}%`, 25, yPos);
          yPos += 10;
        }
      });
      
      // Add section for recommendations
      doc.setFontSize(14);
      doc.text('Improvement Recommendations:', 20, yPos + 10);
      
      // Add recommendations
      yPos += 20;
      tips.forEach((tip, index) => {
        // Check if we need a new page
        if (yPos > pageHeight - 30) {
          doc.addPage();
          yPos = 30;
        }
        
        doc.setFontSize(12);
        doc.setTextColor(0, 48, 87);
        doc.text(`${index + 1}. ${tip.title || tip.text}`, 25, yPos);
        yPos += 10;
        
        // Text wrapping for description
        const splitText = doc.splitTextToSize(tip.description || tip.text, pageWidth - 50);
        doc.setFontSize(10);
        doc.text(splitText, 30, yPos);
        yPos += (splitText.length * 6) + 10;
      });
    } else {
      // Free tier gets minimal information
      doc.setFontSize(14);
      doc.text('Upgrade to Premium for detailed scores and recommendations!', 20, 90);
      
      // Show only 2 tips for free users
      if (tips.length > 0) {
        doc.text('Top Improvement Tips:', 20, 110);
        
        const limitedTips = tips.slice(0, 2);
        let yPos = 120;
        
        limitedTips.forEach((tip, index) => {
          doc.setFontSize(12);
          doc.text(`${index + 1}. ${tip.title || tip.text}`, 25, yPos);
          yPos += 10;
          
          const splitText = doc.splitTextToSize(tip.description || tip.text, pageWidth - 50);
          doc.setFontSize(10);
          doc.text(splitText, 30, yPos);
          yPos += (splitText.length * 6) + 10;
        });
      }
    }
    
    // Add footer
    const footerY = pageHeight - 20;
    doc.setFontSize(10);
    doc.setTextColor(128, 128, 128);
    doc.text('Generated by ATSBoost - atsboost.co.za', pageWidth / 2, footerY, { align: 'center' });
    doc.text(new Date().toLocaleDateString(), pageWidth - 20, footerY, { align: 'right' });
    
    // Save the PDF
    doc.save('ATSBoost-CV-Report.pdf');
  } catch (error) {
    console.error('Error generating PDF report:', error);
    throw new Error('Failed to generate PDF report');
  }
};
